/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pandateam.sfsaludmaven.gui;

import com.pandateam.sfsaludmaven.gui.panels.*;
import java.awt.BorderLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author santi
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private void ShowPanel(JPanel pan) {
        pan.setSize(650, 570);
        pan.setLocation(0, 0);

        jPanContentPrincipal.removeAll();
        jPanContentPrincipal.add(pan, BorderLayout.CENTER);
        jPanContentPrincipal.revalidate();
        jPanContentPrincipal.repaint();
    }

    public MainFrame() {

        //ImageIcon imgLogo = new ImageIcon (getClass().getResource("/Images/logo.png"));
        initComponents();
        setLocationRelativeTo(null);

        JPanAdmBienvenida pan = new JPanAdmBienvenida();
        ShowPanel(pan);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanNavBar = new javax.swing.JPanel();
        jPanButtonServicios = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanButtonCuidadores = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanButtonPacientes = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanButtonInicio = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanContentPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(850, 570));
        setMinimumSize(new java.awt.Dimension(850, 570));
        setName("MainFrame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(850, 570));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanNavBar.setBackground(new java.awt.Color(39, 168, 195));
        jPanNavBar.setMaximumSize(new java.awt.Dimension(200, 570));
        jPanNavBar.setMinimumSize(new java.awt.Dimension(200, 570));
        jPanNavBar.setPreferredSize(new java.awt.Dimension(200, 570));
        jPanNavBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanButtonServicios.setBackground(new java.awt.Color(0, 128, 155));
        jPanButtonServicios.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanButtonServicios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanButtonServicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanButtonServiciosMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Servicios");
        jPanButtonServicios.add(jLabel1);

        jPanNavBar.add(jPanButtonServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 160, 40));

        jLabel2.setFont(new java.awt.Font("Roboto Condensed", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Salud");
        jPanNavBar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 160, 30));

        jLabel3.setFont(new java.awt.Font("Roboto Condensed", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Seleccione para administrar:");
        jPanNavBar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 160, 30));

        jPanButtonCuidadores.setBackground(new java.awt.Color(0, 128, 155));
        jPanButtonCuidadores.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanButtonCuidadores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanButtonCuidadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanButtonCuidadoresMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Cuidadores");
        jPanButtonCuidadores.add(jLabel4);

        jPanNavBar.add(jPanButtonCuidadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 160, 40));

        jPanButtonPacientes.setBackground(new java.awt.Color(0, 128, 155));
        jPanButtonPacientes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanButtonPacientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanButtonPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanButtonPacientesMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Pacientes");
        jPanButtonPacientes.add(jLabel5);

        jPanNavBar.add(jPanButtonPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 160, 40));

        jPanButtonInicio.setBackground(new java.awt.Color(0, 128, 155));
        jPanButtonInicio.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanButtonInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanButtonInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanButtonInicioMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Inicio");
        jPanButtonInicio.add(jLabel6);

        jPanNavBar.add(jPanButtonInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 160, 40));

        jLabel7.setFont(new java.awt.Font("Roboto Condensed", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("San Francisco");
        jPanNavBar.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 160, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        jPanNavBar.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg2.png"))); // NOI18N
        jPanNavBar.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 570));

        getContentPane().add(jPanNavBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 570));

        jPanContentPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        jPanContentPrincipal.setMaximumSize(new java.awt.Dimension(650, 570));
        jPanContentPrincipal.setMinimumSize(new java.awt.Dimension(650, 570));
        jPanContentPrincipal.setPreferredSize(new java.awt.Dimension(650, 570));
        getContentPane().add(jPanContentPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 650, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanButtonCuidadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanButtonCuidadoresMouseClicked
        // TODO add your handling code here:
        JPanAdmCuidadores pan = new JPanAdmCuidadores();
        ShowPanel(pan);
    }//GEN-LAST:event_jPanButtonCuidadoresMouseClicked

    private void jPanButtonPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanButtonPacientesMouseClicked
        // TODO add your handling code here:
        JPanAdmPacientes pan = new JPanAdmPacientes();
        ShowPanel(pan);
    }//GEN-LAST:event_jPanButtonPacientesMouseClicked

    private void jPanButtonServiciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanButtonServiciosMouseClicked
        // TODO add your handling code here:
        JPanAdmServicios pan = new JPanAdmServicios();
        ShowPanel(pan);
    }//GEN-LAST:event_jPanButtonServiciosMouseClicked

    private void jPanButtonInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanButtonInicioMouseClicked
        // TODO add your handling code here:
        JPanAdmBienvenida pan = new JPanAdmBienvenida();
        ShowPanel(pan);
    }//GEN-LAST:event_jPanButtonInicioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanButtonCuidadores;
    private javax.swing.JPanel jPanButtonInicio;
    private javax.swing.JPanel jPanButtonPacientes;
    private javax.swing.JPanel jPanButtonServicios;
    private javax.swing.JPanel jPanContentPrincipal;
    private javax.swing.JPanel jPanNavBar;
    // End of variables declaration//GEN-END:variables
}
