/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pandateam.sfsaludmaven.gui.panels;

import com.pandateam.sfsaludmaven.backend.dto.PacienteDTO;
import com.pandateam.sfsaludmaven.backend.dto.SuscripcionDTO;
import com.pandateam.sfsaludmaven.backend.managers.NoSocioManager;
import com.pandateam.sfsaludmaven.backend.managers.PacienteManager;
import com.pandateam.sfsaludmaven.backend.managers.SocioManager;
import com.pandateam.sfsaludmaven.backend.managers.SuscripcionManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author biane
 */
public class JPanAdmSuscripcionAsignar extends javax.swing.JPanel {

    /**
     * Creates new form JPanAdmPacientesConsultar
     */
    private Object[] o = new Object[5];

    public JPanAdmSuscripcionAsignar() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConsultaPaciente = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabNombreTitular = new javax.swing.JLabel();
        jTextFieldDNITitular = new javax.swing.JTextField();
        jButtBuscarDNI = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabResultadoBusqueda = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabFechaInicio = new javax.swing.JLabel();
        jLabTipoPlan = new javax.swing.JLabel();
        jLabDescuento = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButtAsignarSuscripcion = new javax.swing.JButton();
        jTextFieldDNINoMiembro = new javax.swing.JTextField();
        jButtonBuscarNoSocio = new javax.swing.JButton();

        jLabel4.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Nombre:");

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(650, 456));
        setMinimumSize(new java.awt.Dimension(650, 456));
        setPreferredSize(new java.awt.Dimension(650, 456));

        jLabel1.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Asignar suscripción a un paciente");

        jTableConsultaPaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "DNI", "N° Socio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableConsultaPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableConsultaPacienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableConsultaPaciente);

        jLabel3.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Agregar Miembro:");

        jLabel5.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("DNI del Titular:");

        jLabel6.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Fecha de inicio:");

        jLabel7.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Nombre del titular:");

        jLabNombreTitular.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabNombreTitular.setForeground(new java.awt.Color(102, 102, 102));
        jLabNombreTitular.setText("-");

        jButtBuscarDNI.setText("Buscar");
        jButtBuscarDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtBuscarDNIActionPerformed(evt);
            }
        });

        jLabResultadoBusqueda.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabResultadoBusqueda.setForeground(new java.awt.Color(102, 102, 102));
        jLabResultadoBusqueda.setText("-");

        jLabel2.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Datos Suscripción");

        jLabFechaInicio.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabFechaInicio.setForeground(new java.awt.Color(102, 102, 102));
        jLabFechaInicio.setText("-");

        jLabTipoPlan.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabTipoPlan.setForeground(new java.awt.Color(102, 102, 102));
        jLabTipoPlan.setText("-");

        jLabDescuento.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabDescuento.setForeground(new java.awt.Color(102, 102, 102));
        jLabDescuento.setText("-");

        jLabel8.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Tipo de Plan:");

        jLabel9.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Descuento (%):");

        jLabel10.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Grado de Parentesco:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01 - Cónyuge", "02 al 15 - Hijos", "16 al 30 - Mayores a cargo", "31 al 99 - Otros miembros a cargo" }));
        jComboBox1.setToolTipText("");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButtAsignarSuscripcion.setText("Agregar");
        jButtAsignarSuscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtAsignarSuscripcionActionPerformed(evt);
            }
        });

        jButtonBuscarNoSocio.setText("Buscar");
        jButtonBuscarNoSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarNoSocioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldDNINoMiembro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonBuscarNoSocio))
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabNombreTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabTipoPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(249, 249, 249)
                                .addComponent(jButtAsignarSuscripcion))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldDNITitular, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addComponent(jButtBuscarDNI)
                                    .addGap(44, 44, 44)
                                    .addComponent(jLabResultadoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldDNITitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtBuscarDNI)
                    .addComponent(jLabResultadoBusqueda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabNombreTitular))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabFechaInicio)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabTipoPlan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabDescuento))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldDNINoMiembro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarNoSocio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtAsignarSuscripcion)
                .addContainerGap(11, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTableConsultaPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableConsultaPacienteMouseClicked

    }//GEN-LAST:event_jTableConsultaPacienteMouseClicked

    private void jButtBuscarDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtBuscarDNIActionPerformed
        try {
            SuscripcionDTO suscripcion = SuscripcionManager.encontrarPorTitular(jTextFieldDNITitular.getText());
            PacienteDTO paciente = PacienteManager.verPacientePorDNI(jTextFieldDNITitular.getText());
            jLabNombreTitular.setText(paciente.getNombre() + paciente.getApellido());
            jLabFechaInicio.setText("" + suscripcion.getFechaInicio());
            jLabTipoPlan.setText(suscripcion.getEstado());
            jLabDescuento.setText("" + suscripcion.getDescuento());

            DefaultTableModel table = NoSocioManager.consultarNoSocio("");
            jTableConsultaPaciente.setModel(table);

        } catch (SQLException ex) {
            Logger.getLogger(JPanAdmSuscripcionAsignar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtBuscarDNIActionPerformed


    private void jButtAsignarSuscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtAsignarSuscripcionActionPerformed
        try {
            
            int selectedRow = jTableConsultaPaciente.getSelectedRow();
            Object object = jTableConsultaPaciente.getValueAt(selectedRow, 0);
            int idPacienteSeleccionado = Integer.parseInt(object.toString());
            int index = jComboBox1.getSelectedIndex();
            SuscripcionDTO suscripcion = SuscripcionManager.encontrarPorTitular(jTextFieldDNITitular.getText());
            PacienteDTO paciente = PacienteManager.verPaciente(idPacienteSeleccionado);
            
            //System.out.println(""+paciente);
            
            SocioManager.asignarSuscripcion(paciente, suscripcion, index);
        } catch (SQLException ex) {
            Logger.getLogger(JPanAdmSuscripcionAsignar.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtAsignarSuscripcionActionPerformed

    private void jButtonBuscarNoSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarNoSocioActionPerformed
        try {
            DefaultTableModel table = NoSocioManager.consultarNoSocio(jTextFieldDNINoMiembro.getText());
            jTableConsultaPaciente.setModel(table);
        } catch (SQLException ex) {
            Logger.getLogger(JPanAdmSuscripcionAsignar.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonBuscarNoSocioActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        //System.out.println("" + jComboBox1.getSelectedIndex());
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtAsignarSuscripcion;
    private javax.swing.JButton jButtBuscarDNI;
    private javax.swing.JButton jButtonBuscarNoSocio;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabDescuento;
    private javax.swing.JLabel jLabFechaInicio;
    private javax.swing.JLabel jLabNombreTitular;
    private javax.swing.JLabel jLabResultadoBusqueda;
    private javax.swing.JLabel jLabTipoPlan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTableConsultaPaciente;
    private javax.swing.JTextField jTextFieldDNINoMiembro;
    private javax.swing.JTextField jTextFieldDNITitular;
    // End of variables declaration//GEN-END:variables
}
