/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pandateam.sfsaludmaven.gui.panels;

import com.pandateam.sfsaludmaven.gui.GUIFunctions;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author biane
 */
public class JPanAdmServicioConsultarBase extends javax.swing.JPanel {

    /**
     * Creates new form JPanAdmPacientesConsultar
     */
    private JPanAdmServicioConsultar panelConsultar;
    
    
    public JPanAdmServicioConsultarBase() throws SQLException {
        initComponents();
        panelConsultar = new JPanAdmServicioConsultar();
        JPanAdmServicioConsultar pan = new JPanAdmServicioConsultar();
        panelConsultar = pan;
        GUIFunctions.showPanel(pan, JPanelContentConsServicio, 650, 456);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        JPanelContentConsServicio = new javax.swing.JPanel();
        jButtonSiguiente = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();

        jLabel4.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Nombre:");

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(650, 500));
        setMinimumSize(new java.awt.Dimension(650, 500));

        JPanelContentConsServicio.setBackground(new java.awt.Color(255, 255, 255));
        JPanelContentConsServicio.setMaximumSize(new java.awt.Dimension(650, 456));
        JPanelContentConsServicio.setMinimumSize(new java.awt.Dimension(650, 456));

        javax.swing.GroupLayout JPanelContentConsServicioLayout = new javax.swing.GroupLayout(JPanelContentConsServicio);
        JPanelContentConsServicio.setLayout(JPanelContentConsServicioLayout);
        JPanelContentConsServicioLayout.setHorizontalGroup(
            JPanelContentConsServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        JPanelContentConsServicioLayout.setVerticalGroup(
            JPanelContentConsServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
        );

        jButtonSiguiente.setText("Siguiente");
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteActionPerformed(evt);
            }
        });

        jButtonAnterior.setText("Anterior");
        jButtonAnterior.setEnabled(false);
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPanelContentConsServicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButtonAnterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSiguiente)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPanelContentConsServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSiguiente)
                    .addComponent(jButtonAnterior))
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteActionPerformed
        // TODO add your handling code here:
        //JPanAdmServicioConsultar2 pan2 = new JPanAdmServicioConsultar2();
        //GUIFunctions.showPanel(pan2, JPanelContentConsServicio, 650, 456);
        
        int servicioID = panelConsultar.getServicioIDSeleccionado();
        System.out.println(""+servicioID);
        if (servicioID == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona un servicio antes de continuar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {
            panelConsultar.getPanel2().setServicioID(servicioID);
            GUIFunctions.showPanel(panelConsultar.getPanel2(), JPanelContentConsServicio, 650, 456);
            jButtonAnterior.setEnabled(true);
            jButtonSiguiente.setEnabled(false);
        }
        
        

    }//GEN-LAST:event_jButtonSiguienteActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        // TODO add your handling code here:
        GUIFunctions.showPanel(panelConsultar, JPanelContentConsServicio, 650, 456);
        jButtonAnterior.setEnabled(false);
        jButtonSiguiente.setEnabled(true);
    }//GEN-LAST:event_jButtonAnteriorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelContentConsServicio;
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
