/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pandateam.sfsaludmaven.gui.panels;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author biane
 */
public class JPanAdmServiciosCargar extends javax.swing.JPanel {

    private void ShowPanel (JPanel pan){
        pan.setSize(638, 457);
        pan.setLocation(0,0);
        
        jPanTabConsultarPaciente.removeAll();
        jPanTabConsultarPaciente.add(pan, BorderLayout.CENTER);
        jPanTabConsultarPaciente.revalidate();
        jPanTabConsultarPaciente.repaint();
    }
    
    public JPanAdmServiciosCargar() {
        initComponents();
        JPanAdmEnConstruccion pan = new JPanAdmEnConstruccion();
        ShowPanel(pan);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanTabDatosServicio1 = new javax.swing.JPanel();
        jCBTipoServicio1 = new javax.swing.JComboBox<>();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jSpinner4 = new javax.swing.JSpinner();
        jDateChooser4 = new com.toedter.calendar.JDateChooser();
        jSpinner5 = new javax.swing.JSpinner();
        jSpinner6 = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButtSiguienteIngreso1 = new javax.swing.JButton();
        jTabbedPaneCargarServicios = new javax.swing.JTabbedPane();
        jPanTabDatosServicio = new javax.swing.JPanel();
        jCBTipoServicio = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jSpinner1 = new javax.swing.JSpinner();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButtSiguienteIngreso = new javax.swing.JButton();
        jButtCalcular = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanTabConsultarPaciente = new javax.swing.JPanel();
        jPanTabConsultarCuidador = new javax.swing.JPanel();
        jPanTabConfirmacion = new javax.swing.JPanel();

        jLabel3.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Tipo de Servicio:");

        jPanTabDatosServicio1.setBackground(new java.awt.Color(255, 255, 255));

        jCBTipoServicio1.setBackground(new java.awt.Color(255, 255, 255));
        jCBTipoServicio1.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        jCBTipoServicio1.setForeground(new java.awt.Color(0, 0, 0));
        jCBTipoServicio1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuidador Interno", "Cuidador Externo", "Cuidador Nocturno", "Acompañamiento", "Cuidado de niños", "Cuidador de fin de semana" }));

        jLabel8.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("Tipo de Servicio:");

        jLabel9.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setText("Fecha de Inicio:");

        jLabel10.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setText("Fecha de Finalización:");

        jLabel11.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 102));
        jLabel11.setText("Cantidad de Atenciones:");

        jLabel12.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 102));
        jLabel12.setText("Cantidad de Horas por día:");

        jLabel13.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 102));
        jLabel13.setText("Costo por Hora establecido:");

        jButtSiguienteIngreso1.setBackground(new java.awt.Color(0, 153, 153));
        jButtSiguienteIngreso1.setForeground(new java.awt.Color(255, 255, 255));
        jButtSiguienteIngreso1.setText("Siguiente");
        jButtSiguienteIngreso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtSiguienteIngreso1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanTabDatosServicio1Layout = new javax.swing.GroupLayout(jPanTabDatosServicio1);
        jPanTabDatosServicio1.setLayout(jPanTabDatosServicio1Layout);
        jPanTabDatosServicio1Layout.setHorizontalGroup(
            jPanTabDatosServicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanTabDatosServicio1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanTabDatosServicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanTabDatosServicio1Layout.createSequentialGroup()
                        .addGroup(jPanTabDatosServicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanTabDatosServicio1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(6, 6, 6))
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanTabDatosServicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCBTipoServicio1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSpinner4)
                    .addComponent(jSpinner5)
                    .addComponent(jSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(293, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanTabDatosServicio1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtSiguienteIngreso1)
                .addGap(24, 24, 24))
        );
        jPanTabDatosServicio1Layout.setVerticalGroup(
            jPanTabDatosServicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanTabDatosServicio1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanTabDatosServicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBTipoServicio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanTabDatosServicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanTabDatosServicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanTabDatosServicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanTabDatosServicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanTabDatosServicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addComponent(jButtSiguienteIngreso1)
                .addContainerGap())
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(650, 500));
        setMinimumSize(new java.awt.Dimension(650, 500));

        jTabbedPaneCargarServicios.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPaneCargarServicios.setForeground(new java.awt.Color(0, 0, 102));
        jTabbedPaneCargarServicios.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jTabbedPaneCargarServicios.setMinimumSize(new java.awt.Dimension(638, 488));

        jPanTabDatosServicio.setBackground(new java.awt.Color(255, 255, 255));
        jPanTabDatosServicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCBTipoServicio.setBackground(new java.awt.Color(255, 255, 255));
        jCBTipoServicio.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        jCBTipoServicio.setForeground(new java.awt.Color(0, 0, 0));
        jCBTipoServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuidador Interno", "Cuidador Externo", "Cuidador Nocturno", "Acompañamiento", "Cuidado de niños", "Cuidador de fin de semana" }));
        jPanTabDatosServicio.add(jCBTipoServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));
        jPanTabDatosServicio.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 164, -1));
        jPanTabDatosServicio.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 171, 164, -1));
        jPanTabDatosServicio.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 164, -1));
        jPanTabDatosServicio.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 211, 164, -1));
        jPanTabDatosServicio.add(jSpinner3, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 251, 164, -1));

        jLabel1.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Tipo de Servicio:");
        jPanTabDatosServicio.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 143, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Fecha de Inicio:");
        jPanTabDatosServicio.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 143, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Fecha de Finalización:");
        jPanTabDatosServicio.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 143, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Cantidad de Atenciones:");
        jPanTabDatosServicio.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 174, 143, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("Cantidad de Horas por día:");
        jPanTabDatosServicio.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 214, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Costo por Hora establecido:");
        jPanTabDatosServicio.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 254, -1, -1));

        jButtSiguienteIngreso.setBackground(new java.awt.Color(0, 153, 153));
        jButtSiguienteIngreso.setForeground(new java.awt.Color(255, 255, 255));
        jButtSiguienteIngreso.setText("Siguiente");
        jButtSiguienteIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtSiguienteIngresoActionPerformed(evt);
            }
        });
        jPanTabDatosServicio.add(jButtSiguienteIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 428, -1, -1));

        jButtCalcular.setBackground(new java.awt.Color(0, 153, 153));
        jButtCalcular.setForeground(new java.awt.Color(255, 255, 255));
        jButtCalcular.setText("Calcular");
        jButtCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtCalcularActionPerformed(evt);
            }
        });
        jPanTabDatosServicio.add(jButtCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 291, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel14.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("El costo total del servicio es de:");

        jLabel15.setFont(new java.awt.Font("Roboto Condensed", 0, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 102));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("$00000");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jPanTabDatosServicio.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 230, 220));

        jTabbedPaneCargarServicios.addTab("Ingrese los datos", jPanTabDatosServicio);

        jPanTabConsultarPaciente.setMaximumSize(new java.awt.Dimension(638, 457));
        jPanTabConsultarPaciente.setMinimumSize(new java.awt.Dimension(638, 457));

        javax.swing.GroupLayout jPanTabConsultarPacienteLayout = new javax.swing.GroupLayout(jPanTabConsultarPaciente);
        jPanTabConsultarPaciente.setLayout(jPanTabConsultarPacienteLayout);
        jPanTabConsultarPacienteLayout.setHorizontalGroup(
            jPanTabConsultarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
        );
        jPanTabConsultarPacienteLayout.setVerticalGroup(
            jPanTabConsultarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
        );

        jTabbedPaneCargarServicios.addTab("Elija un paciente", jPanTabConsultarPaciente);

        javax.swing.GroupLayout jPanTabConsultarCuidadorLayout = new javax.swing.GroupLayout(jPanTabConsultarCuidador);
        jPanTabConsultarCuidador.setLayout(jPanTabConsultarCuidadorLayout);
        jPanTabConsultarCuidadorLayout.setHorizontalGroup(
            jPanTabConsultarCuidadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
        );
        jPanTabConsultarCuidadorLayout.setVerticalGroup(
            jPanTabConsultarCuidadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
        );

        jTabbedPaneCargarServicios.addTab("Elija un cuidador", jPanTabConsultarCuidador);

        jPanTabConfirmacion.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanTabConfirmacionLayout = new javax.swing.GroupLayout(jPanTabConfirmacion);
        jPanTabConfirmacion.setLayout(jPanTabConfirmacionLayout);
        jPanTabConfirmacionLayout.setHorizontalGroup(
            jPanTabConfirmacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
        );
        jPanTabConfirmacionLayout.setVerticalGroup(
            jPanTabConfirmacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
        );

        jTabbedPaneCargarServicios.addTab("Confirmación", jPanTabConfirmacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneCargarServicios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneCargarServicios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtSiguienteIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtSiguienteIngresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtSiguienteIngresoActionPerformed

    private void jButtSiguienteIngreso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtSiguienteIngreso1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtSiguienteIngreso1ActionPerformed

    private void jButtCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtCalcularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtCalcularActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtCalcular;
    private javax.swing.JButton jButtSiguienteIngreso;
    private javax.swing.JButton jButtSiguienteIngreso1;
    private javax.swing.JComboBox<String> jCBTipoServicio;
    private javax.swing.JComboBox<String> jCBTipoServicio1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private com.toedter.calendar.JDateChooser jDateChooser4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanTabConfirmacion;
    private javax.swing.JPanel jPanTabConsultarCuidador;
    private javax.swing.JPanel jPanTabConsultarPaciente;
    private javax.swing.JPanel jPanTabDatosServicio;
    private javax.swing.JPanel jPanTabDatosServicio1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner6;
    private javax.swing.JTabbedPane jTabbedPaneCargarServicios;
    // End of variables declaration//GEN-END:variables
}
