/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pandateam.sfsaludmaven.gui.panels;

import com.pandateam.sfsaludmaven.backend.dto.CuidadorDTO;
import com.pandateam.sfsaludmaven.backend.dto.PacienteDTO;
import com.pandateam.sfsaludmaven.backend.dto.ServicioDTO;
import com.pandateam.sfsaludmaven.backend.managers.CuidadorManager;
import com.pandateam.sfsaludmaven.backend.managers.PacienteManager;
import java.awt.BorderLayout;
import javax.swing.JPanel;
import com.pandateam.sfsaludmaven.backend.managers.ServicioManager;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author biane
 */
public class JPanAdmServiciosCargar extends javax.swing.JPanel {

    private static ServicioDTO dto = new ServicioDTO();
    private double precio = 0;
    private JPanAdmPacientesConsultar pacientes = new JPanAdmPacientesConsultar();
    private JPanAdmCuidadoresConsultar cuidadores = new JPanAdmCuidadoresConsultar();
    private ServicioManager servicioManager = new ServicioManager();

    public void setPrecio(double x) {
        this.precio = x;
    }

    public double getPrecio() {
        return precio;
    }

    public void setDTO(ServicioDTO dto) {
        this.dto = dto;
    }

    public ServicioDTO getDTO() {
        return dto;
    }

    private void ShowPanel(JPanel pan, JPanel insertable) {
        pan.setSize(638, 457);
        pan.setLocation(0, 0);

        //insertable.removeAll();
        insertable.add(pan, BorderLayout.CENTER);
        insertable.revalidate();
        insertable.repaint();
    }

    public JPanAdmServiciosCargar() {

        initComponents();
        JDCFechaInicio.setMinSelectableDate(new Date());
        JDCFechaFin.setMinSelectableDate(new Date());

        ShowPanel(pacientes, jPanTabConsultarPaciente);
        ShowPanel(cuidadores, jPanTabConsultarCuidador);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanTabDatosServicio1 = new javax.swing.JPanel();
        jCBTipoServicio1 = new javax.swing.JComboBox<>();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jSpinner4 = new javax.swing.JSpinner();
        jDateChooser4 = new com.toedter.calendar.JDateChooser();
        jSpinner5 = new javax.swing.JSpinner();
        jSpinner6 = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButtSiguienteIngreso1 = new javax.swing.JButton();
        jTabbedPaneCargarServicios = new javax.swing.JTabbedPane();
        jPanTabDatosServicio = new javax.swing.JPanel();
        jCBTipoServicio = new javax.swing.JComboBox<>();
        JDCFechaInicio = new com.toedter.calendar.JDateChooser();
        JSpinCantAtenciones = new javax.swing.JSpinner();
        JDCFechaFin = new com.toedter.calendar.JDateChooser();
        jSpinCantHorasDia = new javax.swing.JSpinner();
        JSpinCostoHora = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButtSiguiente1 = new javax.swing.JButton();
        jPanCostoServicio = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabCostoServicio = new javax.swing.JLabel();
        jButtCalcular1 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDesc = new javax.swing.JTextArea();
        jPanTabConsultarPaciente = new javax.swing.JPanel();
        jButtSiguiente4 = new javax.swing.JButton();
        jButtSiguiente5 = new javax.swing.JButton();
        jPanTabConsultarCuidador = new javax.swing.JPanel();
        jButtSiguiente2 = new javax.swing.JButton();
        jButtSiguiente6 = new javax.swing.JButton();
        jPanTabConfirmacion = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jButtSiguiente7 = new javax.swing.JButton();
        jButtConfirmar = new javax.swing.JButton();
        jLabConfFInicio = new javax.swing.JLabel();
        jLabConfFFin = new javax.swing.JLabel();
        jLabConfNombrePaciente = new javax.swing.JLabel();
        jLabConfDNIPaciente = new javax.swing.JLabel();
        jLabConfDNICuidador = new javax.swing.JLabel();
        jLabConfNombreCuidador = new javax.swing.JLabel();
        jLabConfApellidoPaciente = new javax.swing.JLabel();
        jLabConfNroSocio = new javax.swing.JLabel();
        jLabConfApellidoCuidador = new javax.swing.JLabel();
        jLabConfProfesionCuidador = new javax.swing.JLabel();
        jLabConfCantAtenciones = new javax.swing.JLabel();
        jLabCostoTotalServicio = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Tipo de Servicio:");

        jPanTabDatosServicio1.setBackground(new java.awt.Color(255, 255, 255));

        jCBTipoServicio1.setBackground(new java.awt.Color(255, 255, 255));
        jCBTipoServicio1.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        jCBTipoServicio1.setForeground(new java.awt.Color(0, 0, 0));
        jCBTipoServicio1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuidador Interno", "Cuidador Externo", "Cuidador Nocturno", "Acompañamiento", "Cuidado de niños", "Cuidador de fin de semana" }));

        jLabel8.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("Tipo de Servicio:");

        jLabel9.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setText("Fecha de Inicio:");

        jLabel10.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setText("Fecha de Finalización:");

        jLabel11.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 102));
        jLabel11.setText("Cantidad de Atenciones:");

        jLabel12.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 102));
        jLabel12.setText("Cantidad de Horas por día:");

        jLabel13.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 102));
        jLabel13.setText("Costo por Hora establecido:");

        jButtSiguienteIngreso1.setBackground(new java.awt.Color(0, 153, 153));
        jButtSiguienteIngreso1.setForeground(new java.awt.Color(255, 255, 255));
        jButtSiguienteIngreso1.setText("Siguiente");
        jButtSiguienteIngreso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtSiguienteIngreso1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanTabDatosServicio1Layout = new javax.swing.GroupLayout(jPanTabDatosServicio1);
        jPanTabDatosServicio1.setLayout(jPanTabDatosServicio1Layout);
        jPanTabDatosServicio1Layout.setHorizontalGroup(
            jPanTabDatosServicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanTabDatosServicio1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanTabDatosServicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanTabDatosServicio1Layout.createSequentialGroup()
                        .addGroup(jPanTabDatosServicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanTabDatosServicio1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(6, 6, 6))
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanTabDatosServicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCBTipoServicio1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSpinner4)
                    .addComponent(jSpinner5)
                    .addComponent(jSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(293, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanTabDatosServicio1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtSiguienteIngreso1)
                .addGap(24, 24, 24))
        );
        jPanTabDatosServicio1Layout.setVerticalGroup(
            jPanTabDatosServicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanTabDatosServicio1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanTabDatosServicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBTipoServicio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanTabDatosServicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanTabDatosServicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanTabDatosServicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanTabDatosServicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanTabDatosServicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addComponent(jButtSiguienteIngreso1)
                .addContainerGap())
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(650, 500));
        setMinimumSize(new java.awt.Dimension(650, 500));

        jTabbedPaneCargarServicios.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPaneCargarServicios.setForeground(new java.awt.Color(0, 0, 102));
        jTabbedPaneCargarServicios.setEnabled(false);
        jTabbedPaneCargarServicios.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jTabbedPaneCargarServicios.setMinimumSize(new java.awt.Dimension(638, 488));
        jTabbedPaneCargarServicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPaneCargarServiciosMouseClicked(evt);
            }
        });

        jPanTabDatosServicio.setBackground(new java.awt.Color(255, 255, 255));
        jPanTabDatosServicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCBTipoServicio.setBackground(new java.awt.Color(255, 255, 255));
        jCBTipoServicio.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        jCBTipoServicio.setForeground(new java.awt.Color(0, 0, 0));
        jCBTipoServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuidador Interno", "Cuidador Externo", "Cuidador Nocturno", "Acompañamiento", "Cuidado de niños", "Cuidador de fin de semana" }));
        jCBTipoServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBTipoServicioActionPerformed(evt);
            }
        });
        jPanTabDatosServicio.add(jCBTipoServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        JDCFechaInicio.setBackground(new java.awt.Color(255, 255, 255));
        JDCFechaInicio.setForeground(new java.awt.Color(0, 0, 0));
        jPanTabDatosServicio.add(JDCFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 164, -1));
        jPanTabDatosServicio.add(JSpinCantAtenciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 171, 164, -1));

        JDCFechaFin.setBackground(new java.awt.Color(255, 255, 255));
        JDCFechaFin.setForeground(new java.awt.Color(0, 0, 0));
        jPanTabDatosServicio.add(JDCFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 164, -1));
        jPanTabDatosServicio.add(jSpinCantHorasDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 211, 164, -1));
        jPanTabDatosServicio.add(JSpinCostoHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 251, 164, -1));

        jLabel1.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Tipo de Servicio:");
        jPanTabDatosServicio.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 143, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Fecha de Inicio:");
        jPanTabDatosServicio.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 143, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Fecha de Finalización:");
        jPanTabDatosServicio.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 143, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Cantidad de Atenciones:");
        jPanTabDatosServicio.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 174, 143, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("Cantidad de Horas por día:");
        jPanTabDatosServicio.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 214, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Costo por Hora establecido:");
        jPanTabDatosServicio.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jButtSiguiente1.setBackground(new java.awt.Color(0, 153, 153));
        jButtSiguiente1.setForeground(new java.awt.Color(255, 255, 255));
        jButtSiguiente1.setText("Siguiente");
        jButtSiguiente1.setEnabled(false);
        jButtSiguiente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtSiguiente1ActionPerformed(evt);
            }
        });
        jPanTabDatosServicio.add(jButtSiguiente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, -1, -1));

        jPanCostoServicio.setBackground(new java.awt.Color(204, 255, 255));

        jLabel14.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("El costo total del servicio es de:");

        jLabCostoServicio.setFont(new java.awt.Font("Roboto Condensed", 0, 48)); // NOI18N
        jLabCostoServicio.setForeground(new java.awt.Color(0, 102, 102));
        jLabCostoServicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabCostoServicio.setText("$00000");

        javax.swing.GroupLayout jPanCostoServicioLayout = new javax.swing.GroupLayout(jPanCostoServicio);
        jPanCostoServicio.setLayout(jPanCostoServicioLayout);
        jPanCostoServicioLayout.setHorizontalGroup(
            jPanCostoServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabCostoServicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );
        jPanCostoServicioLayout.setVerticalGroup(
            jPanCostoServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanCostoServicioLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabCostoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jPanTabDatosServicio.add(jPanCostoServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 230, 220));

        jButtCalcular1.setBackground(new java.awt.Color(0, 153, 153));
        jButtCalcular1.setForeground(new java.awt.Color(255, 255, 255));
        jButtCalcular1.setText("Calcular");
        jButtCalcular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtCalcular1ActionPerformed(evt);
            }
        });
        jPanTabDatosServicio.add(jButtCalcular1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 110, 50));

        jLabel30.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 102));
        jLabel30.setText("Costo por Hora establecido:");
        jPanTabDatosServicio.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 254, -1, -1));

        jTextAreaDesc.setColumns(20);
        jTextAreaDesc.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDesc);

        jPanTabDatosServicio.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 170, 130));

        jTabbedPaneCargarServicios.addTab("Ingrese los datos", jPanTabDatosServicio);

        jPanTabConsultarPaciente.setMaximumSize(new java.awt.Dimension(638, 457));
        jPanTabConsultarPaciente.setMinimumSize(new java.awt.Dimension(638, 457));

        jButtSiguiente4.setBackground(new java.awt.Color(0, 153, 153));
        jButtSiguiente4.setForeground(new java.awt.Color(255, 255, 255));
        jButtSiguiente4.setText("Siguiente");
        jButtSiguiente4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtSiguiente4ActionPerformed(evt);
            }
        });

        jButtSiguiente5.setBackground(new java.awt.Color(0, 153, 153));
        jButtSiguiente5.setForeground(new java.awt.Color(255, 255, 255));
        jButtSiguiente5.setText("Anterior");
        jButtSiguiente5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtSiguiente5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanTabConsultarPacienteLayout = new javax.swing.GroupLayout(jPanTabConsultarPaciente);
        jPanTabConsultarPaciente.setLayout(jPanTabConsultarPacienteLayout);
        jPanTabConsultarPacienteLayout.setHorizontalGroup(
            jPanTabConsultarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanTabConsultarPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtSiguiente5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 474, Short.MAX_VALUE)
                .addComponent(jButtSiguiente4)
                .addContainerGap())
        );
        jPanTabConsultarPacienteLayout.setVerticalGroup(
            jPanTabConsultarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanTabConsultarPacienteLayout.createSequentialGroup()
                .addContainerGap(392, Short.MAX_VALUE)
                .addGroup(jPanTabConsultarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtSiguiente4)
                    .addComponent(jButtSiguiente5))
                .addContainerGap())
        );

        jTabbedPaneCargarServicios.addTab("Elija un paciente", jPanTabConsultarPaciente);

        jButtSiguiente2.setBackground(new java.awt.Color(0, 153, 153));
        jButtSiguiente2.setForeground(new java.awt.Color(255, 255, 255));
        jButtSiguiente2.setText("Siguiente");
        jButtSiguiente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtSiguiente2ActionPerformed(evt);
            }
        });

        jButtSiguiente6.setBackground(new java.awt.Color(0, 153, 153));
        jButtSiguiente6.setForeground(new java.awt.Color(255, 255, 255));
        jButtSiguiente6.setText("Anterior");
        jButtSiguiente6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtSiguiente6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanTabConsultarCuidadorLayout = new javax.swing.GroupLayout(jPanTabConsultarCuidador);
        jPanTabConsultarCuidador.setLayout(jPanTabConsultarCuidadorLayout);
        jPanTabConsultarCuidadorLayout.setHorizontalGroup(
            jPanTabConsultarCuidadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanTabConsultarCuidadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtSiguiente6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 474, Short.MAX_VALUE)
                .addComponent(jButtSiguiente2)
                .addContainerGap())
        );
        jPanTabConsultarCuidadorLayout.setVerticalGroup(
            jPanTabConsultarCuidadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanTabConsultarCuidadorLayout.createSequentialGroup()
                .addContainerGap(392, Short.MAX_VALUE)
                .addGroup(jPanTabConsultarCuidadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtSiguiente2)
                    .addComponent(jButtSiguiente6))
                .addContainerGap())
        );

        jTabbedPaneCargarServicios.addTab("Elija un cuidador", jPanTabConsultarCuidador);

        jPanTabConfirmacion.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Roboto Condensed", 3, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 102));
        jLabel15.setText("Datos del servicio");

        jLabel16.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 102));
        jLabel16.setText("Fecha de Inicio:");

        jLabel17.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 102));
        jLabel17.setText("Fecha de Finalización:");

        jLabel18.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 102));
        jLabel18.setText("Cantidad de atenciones:");

        jLabel19.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 102));
        jLabel19.setText("Costo total del servicio:");

        jLabel20.setFont(new java.awt.Font("Roboto Condensed", 3, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 102, 102));
        jLabel20.setText("Datos del paciente:");

        jLabel21.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 102));
        jLabel21.setText("N° de Socio:");

        jLabel22.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 102));
        jLabel22.setText("Apellido:");

        jLabel23.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 102));
        jLabel23.setText("DNI:");

        jLabel24.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 102));
        jLabel24.setText("Nombre:");

        jLabel25.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 102));
        jLabel25.setText("Profesión:");

        jLabel26.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 102));
        jLabel26.setText("Apellido:");

        jLabel27.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 102));
        jLabel27.setText("DNI:");

        jLabel28.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 102));
        jLabel28.setText("Nombre:");

        jLabel29.setFont(new java.awt.Font("Roboto Condensed", 3, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 102, 102));
        jLabel29.setText("Datos del cuidador:");

        jButtSiguiente7.setBackground(new java.awt.Color(0, 153, 153));
        jButtSiguiente7.setForeground(new java.awt.Color(255, 255, 255));
        jButtSiguiente7.setText("Anterior");
        jButtSiguiente7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtSiguiente7ActionPerformed(evt);
            }
        });

        jButtConfirmar.setBackground(new java.awt.Color(0, 153, 153));
        jButtConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        jButtConfirmar.setText("Confirmar");
        jButtConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtConfirmarActionPerformed(evt);
            }
        });

        jLabConfFInicio.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabConfFInicio.setForeground(new java.awt.Color(0, 0, 0));

        jLabConfFFin.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabConfFFin.setForeground(new java.awt.Color(0, 0, 0));

        jLabConfNombrePaciente.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabConfNombrePaciente.setForeground(new java.awt.Color(0, 0, 0));

        jLabConfDNIPaciente.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabConfDNIPaciente.setForeground(new java.awt.Color(0, 0, 0));

        jLabConfDNICuidador.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabConfDNICuidador.setForeground(new java.awt.Color(0, 0, 0));

        jLabConfNombreCuidador.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabConfNombreCuidador.setForeground(new java.awt.Color(0, 0, 0));

        jLabConfApellidoPaciente.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabConfApellidoPaciente.setForeground(new java.awt.Color(0, 0, 0));

        jLabConfNroSocio.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabConfNroSocio.setForeground(new java.awt.Color(0, 0, 0));

        jLabConfApellidoCuidador.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabConfApellidoCuidador.setForeground(new java.awt.Color(0, 0, 0));

        jLabConfProfesionCuidador.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabConfProfesionCuidador.setForeground(new java.awt.Color(0, 0, 0));

        jLabConfCantAtenciones.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabConfCantAtenciones.setForeground(new java.awt.Color(0, 0, 0));

        jLabCostoTotalServicio.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabCostoTotalServicio.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanTabConfirmacionLayout = new javax.swing.GroupLayout(jPanTabConfirmacion);
        jPanTabConfirmacion.setLayout(jPanTabConfirmacionLayout);
        jPanTabConfirmacionLayout.setHorizontalGroup(
            jPanTabConfirmacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanTabConfirmacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanTabConfirmacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(jPanTabConfirmacionLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabConfFInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addGroup(jPanTabConfirmacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanTabConfirmacionLayout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabConfCantAtenciones, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanTabConfirmacionLayout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabCostoTotalServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel20)
                    .addGroup(jPanTabConfirmacionLayout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabConfFFin, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanTabConfirmacionLayout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabConfNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addGroup(jPanTabConfirmacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanTabConfirmacionLayout.createSequentialGroup()
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabConfApellidoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanTabConfirmacionLayout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabConfNroSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanTabConfirmacionLayout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabConfDNIPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel29)
                    .addGroup(jPanTabConfirmacionLayout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabConfNombreCuidador, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addGroup(jPanTabConfirmacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanTabConfirmacionLayout.createSequentialGroup()
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabConfApellidoCuidador, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanTabConfirmacionLayout.createSequentialGroup()
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabConfProfesionCuidador, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanTabConfirmacionLayout.createSequentialGroup()
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabConfDNICuidador, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(jPanTabConfirmacionLayout.createSequentialGroup()
                .addComponent(jButtSiguiente7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtConfirmar)
                .addContainerGap())
        );
        jPanTabConfirmacionLayout.setVerticalGroup(
            jPanTabConfirmacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanTabConfirmacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanTabConfirmacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanTabConfirmacionLayout.createSequentialGroup()
                        .addGroup(jPanTabConfirmacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabConfCantAtenciones, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanTabConfirmacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addComponent(jLabCostoTotalServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanTabConfirmacionLayout.createSequentialGroup()
                        .addGroup(jPanTabConfirmacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabConfFInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanTabConfirmacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jLabConfFFin, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanTabConfirmacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanTabConfirmacionLayout.createSequentialGroup()
                        .addGroup(jPanTabConfirmacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22)
                            .addComponent(jLabConfApellidoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanTabConfirmacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21)
                            .addComponent(jLabConfNroSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanTabConfirmacionLayout.createSequentialGroup()
                        .addGroup(jPanTabConfirmacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24)
                            .addComponent(jLabConfNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanTabConfirmacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23)
                            .addComponent(jLabConfDNIPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanTabConfirmacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabConfProfesionCuidador, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanTabConfirmacionLayout.createSequentialGroup()
                        .addGroup(jPanTabConfirmacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanTabConfirmacionLayout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanTabConfirmacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabConfApellidoCuidador, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanTabConfirmacionLayout.createSequentialGroup()
                                .addComponent(jLabConfNombreCuidador, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)))
                        .addGroup(jPanTabConfirmacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabConfDNICuidador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addGroup(jPanTabConfirmacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtSiguiente7)
                    .addComponent(jButtConfirmar))
                .addContainerGap())
        );

        jTabbedPaneCargarServicios.addTab("Confirmación", jPanTabConfirmacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneCargarServicios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneCargarServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtSiguienteIngreso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtSiguienteIngreso1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtSiguienteIngreso1ActionPerformed

    private void jButtSiguiente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtSiguiente1ActionPerformed

        jTabbedPaneCargarServicios.setSelectedIndex(1);


    }//GEN-LAST:event_jButtSiguiente1ActionPerformed

    private void jTabbedPaneCargarServiciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPaneCargarServiciosMouseClicked
    }//GEN-LAST:event_jTabbedPaneCargarServiciosMouseClicked

    private void jButtCalcular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtCalcular1ActionPerformed
        // TODO add your handling code here:
        //((Integer)JSpinCantAtenciones.getValue()).intValue(),((Integer)jSpinCantHorasDia.getValue()).intValue(),
        int cantAtenciones = ((Integer) JSpinCantAtenciones.getValue());
        int cantHorasDia = ((Integer) jSpinCantHorasDia.getValue());

        // Convertir el valor de JSpinCostoHora a Double correctamente
        Number costoHoraValue = (Number) JSpinCostoHora.getValue(); // Esto manejará tanto Integer como Double
        double costoHora = costoHoraValue.doubleValue(); // Convertir a double

        double precioServ = ServicioManager.calcularHorasServicio(
                cantAtenciones,
                cantHorasDia,
                costoHora
        );

        setPrecio(precioServ);
        jLabCostoServicio.setText("$" + precioServ);
        dto.setFechaInicio(JDCFechaInicio.getDate());
        dto.setFechaFin(JDCFechaFin.getDate());
        dto.setDescripcion(jTextAreaDesc.getText());
        dto.setTipoServicio(jCBTipoServicio.getItemAt(jCBTipoServicio.getSelectedIndex()).toString());
        dto.setCosto(precioServ);
        
        //activo el boton siguiente
        jButtSiguiente1.setEnabled(true);
    }//GEN-LAST:event_jButtCalcular1ActionPerformed

    private void jButtSiguiente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtSiguiente2ActionPerformed
        //Confirmacion del cuidador
        CuidadorDTO cuiDTO = new CuidadorDTO();
        try {
            cuiDTO = CuidadorManager.verCuidador(cuidadores.getIdCuidadorSeleccionado());
        } catch (SQLException ex) {
            Logger.getLogger(JPanAdmServiciosCargar.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabConfNombreCuidador.setText(cuiDTO.getNombre());
        jLabConfApellidoCuidador.setText(cuiDTO.getApellido());
        jLabConfDNICuidador.setText(cuiDTO.getDni());
        jLabConfProfesionCuidador.setText(cuiDTO.getProfesion());
        
        //Confirmacion del servicio
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String fechaInicio = dateFormat.format(dto.getFechaInicio());
        String fechaFin = dateFormat.format(dto.getFechaFin());
        jLabConfFFin.setText(fechaFin);
        jLabConfFInicio.setText(fechaInicio);
        jLabConfCantAtenciones.setText(JSpinCantAtenciones.getValue().toString());
        jLabCostoTotalServicio.setText("$" + dto.getCosto());
        dto.setIdCuidador(cuidadores.getIdCuidadorSeleccionado());
        

        jTabbedPaneCargarServicios.setSelectedIndex(3);
    }//GEN-LAST:event_jButtSiguiente2ActionPerformed

    private void jButtSiguiente4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtSiguiente4ActionPerformed
        //Confirmacion del paciente
        PacienteDTO pacDTO = new PacienteDTO();
        try {
            pacDTO = PacienteManager.verPaciente(pacientes.getIdPacienteSeleccionado());
        } catch (SQLException ex) {
            Logger.getLogger(JPanAdmServiciosCargar.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabConfNombrePaciente.setText(pacDTO.getNombre());
        jLabConfApellidoPaciente.setText(pacDTO.getApellido());
        jLabConfDNIPaciente.setText(pacDTO.getDni());
        jLabConfNroSocio.setText(pacDTO.isSuscrip());
        jTabbedPaneCargarServicios.setSelectedIndex(2);
        dto.setIdPaciente(pacientes.getIdPacienteSeleccionado());
    }//GEN-LAST:event_jButtSiguiente4ActionPerformed

    private void jButtSiguiente5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtSiguiente5ActionPerformed
        jTabbedPaneCargarServicios.setSelectedIndex(0);

    }//GEN-LAST:event_jButtSiguiente5ActionPerformed

    private void jButtSiguiente6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtSiguiente6ActionPerformed
        // TODO add your handling code here:
        jTabbedPaneCargarServicios.setSelectedIndex(1);

    }//GEN-LAST:event_jButtSiguiente6ActionPerformed

    private void jButtSiguiente7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtSiguiente7ActionPerformed
        // TODO add your handling code here:
        jTabbedPaneCargarServicios.setSelectedIndex(2);

    }//GEN-LAST:event_jButtSiguiente7ActionPerformed

    private void jButtConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtConfirmarActionPerformed
        System.out.println(dto.toString());
        servicioManager.agregarServicio(dto);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtConfirmarActionPerformed

    private void jCBTipoServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTipoServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBTipoServicioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JDCFechaFin;
    private com.toedter.calendar.JDateChooser JDCFechaInicio;
    private javax.swing.JSpinner JSpinCantAtenciones;
    private javax.swing.JSpinner JSpinCostoHora;
    private javax.swing.JButton jButtCalcular1;
    private javax.swing.JButton jButtConfirmar;
    private javax.swing.JButton jButtSiguiente1;
    private javax.swing.JButton jButtSiguiente2;
    private javax.swing.JButton jButtSiguiente4;
    private javax.swing.JButton jButtSiguiente5;
    private javax.swing.JButton jButtSiguiente6;
    private javax.swing.JButton jButtSiguiente7;
    private javax.swing.JButton jButtSiguienteIngreso1;
    private javax.swing.JComboBox<String> jCBTipoServicio;
    private javax.swing.JComboBox<String> jCBTipoServicio1;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private com.toedter.calendar.JDateChooser jDateChooser4;
    private javax.swing.JLabel jLabConfApellidoCuidador;
    private javax.swing.JLabel jLabConfApellidoPaciente;
    private javax.swing.JLabel jLabConfCantAtenciones;
    private javax.swing.JLabel jLabConfDNICuidador;
    private javax.swing.JLabel jLabConfDNIPaciente;
    private javax.swing.JLabel jLabConfFFin;
    private javax.swing.JLabel jLabConfFInicio;
    private javax.swing.JLabel jLabConfNombreCuidador;
    private javax.swing.JLabel jLabConfNombrePaciente;
    private javax.swing.JLabel jLabConfNroSocio;
    private javax.swing.JLabel jLabConfProfesionCuidador;
    private javax.swing.JLabel jLabCostoServicio;
    private javax.swing.JLabel jLabCostoTotalServicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanCostoServicio;
    private javax.swing.JPanel jPanTabConfirmacion;
    private javax.swing.JPanel jPanTabConsultarCuidador;
    private javax.swing.JPanel jPanTabConsultarPaciente;
    private javax.swing.JPanel jPanTabDatosServicio;
    private javax.swing.JPanel jPanTabDatosServicio1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinCantHorasDia;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner6;
    private javax.swing.JTabbedPane jTabbedPaneCargarServicios;
    private javax.swing.JTextArea jTextAreaDesc;
    // End of variables declaration//GEN-END:variables
}
