/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pandateam.sfsaludmaven.gui.panels;

import com.pandateam.sfsaludmaven.gui.GUIFunctions;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author biane
 */
public class JPanAdmSuscripciones extends javax.swing.JPanel {

    /**
     * Creates new form JPanAdmServicios
     */
    
    public JPanAdmSuscripciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanContentSuscripciones = new javax.swing.JPanel();
        jPanButtonConsultarSuscripcion = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanButtonAsignarSuscripcion = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(650, 570));
        setMinimumSize(new java.awt.Dimension(650, 570));

        jLabel1.setFont(new java.awt.Font("Roboto Condensed", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setText("Administración de Suscripciones");

        jPanContentSuscripciones.setBackground(new java.awt.Color(255, 255, 255));
        jPanContentSuscripciones.setMaximumSize(new java.awt.Dimension(650, 500));
        jPanContentSuscripciones.setMinimumSize(new java.awt.Dimension(650, 500));
        jPanContentSuscripciones.setPreferredSize(new java.awt.Dimension(650, 500));

        jPanButtonConsultarSuscripcion.setBackground(new java.awt.Color(0, 128, 155));
        jPanButtonConsultarSuscripcion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanButtonConsultarSuscripcion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanButtonConsultarSuscripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanButtonConsultarSuscripcionMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Consultar Suscripción");
        jPanButtonConsultarSuscripcion.add(jLabel5);

        jPanButtonAsignarSuscripcion.setBackground(new java.awt.Color(0, 128, 155));
        jPanButtonAsignarSuscripcion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanButtonAsignarSuscripcion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanButtonAsignarSuscripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanButtonAsignarSuscripcionMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Asignar Suscripción a un Paciente");
        jPanButtonAsignarSuscripcion.add(jLabel6);

        javax.swing.GroupLayout jPanContentSuscripcionesLayout = new javax.swing.GroupLayout(jPanContentSuscripciones);
        jPanContentSuscripciones.setLayout(jPanContentSuscripcionesLayout);
        jPanContentSuscripcionesLayout.setHorizontalGroup(
            jPanContentSuscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanContentSuscripcionesLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(jPanContentSuscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanButtonAsignarSuscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanButtonConsultarSuscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanContentSuscripcionesLayout.setVerticalGroup(
            jPanContentSuscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanContentSuscripcionesLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jPanButtonAsignarSuscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanButtonConsultarSuscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanContentSuscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanContentSuscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPanButtonConsultarSuscripcionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanButtonConsultarSuscripcionMouseClicked
        // TODO add your handling code here:
        JPanAdmSuscripcionConsultar pan = new JPanAdmSuscripcionConsultar();
        GUIFunctions.showPanel(pan, jPanContentSuscripciones,650, 500);
    }//GEN-LAST:event_jPanButtonConsultarSuscripcionMouseClicked

    private void jPanButtonAsignarSuscripcionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanButtonAsignarSuscripcionMouseClicked
        // TODO add your handling code here:
        JPanAdmSuscripcionAgregar pan = new JPanAdmSuscripcionAgregar();
        GUIFunctions.showPanel(pan, jPanContentSuscripciones,650, 500);
        
    }//GEN-LAST:event_jPanButtonAsignarSuscripcionMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanButtonAsignarSuscripcion;
    private javax.swing.JPanel jPanButtonConsultarSuscripcion;
    private javax.swing.JPanel jPanContentSuscripciones;
    // End of variables declaration//GEN-END:variables
}
