/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pandateam.sfsaludmaven.gui.panels;

import com.pandateam.sfsaludmaven.gui.GUIFunctions;


/**
 *
 * @author biane
 */
public class JPanAdmPacientesBaseConsultar extends javax.swing.JPanel {

    /**
     * Creates new form JPanAdmPacientesConsultar
     */
    
    public JPanAdmPacientesBaseConsultar() {
        initComponents();
        JPanAdmPacientesConsultar pan = new JPanAdmPacientesConsultar();
        GUIFunctions.showPanel(pan, jPanelContent,650, 456);
        jButtConsultarSusc.setVisible(true);
        jButtAsignarSusc.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtConsultarSusc = new javax.swing.JButton();
        jButtAsignarSusc = new javax.swing.JButton();
        jPanelContent = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(650, 500));
        setMinimumSize(new java.awt.Dimension(650, 500));

        jButtConsultarSusc.setText("Consultar Suscripción");
        jButtConsultarSusc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtConsultarSuscActionPerformed(evt);
            }
        });

        jButtAsignarSusc.setText("Asignar Suscripción");
        jButtAsignarSusc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtAsignarSuscActionPerformed(evt);
            }
        });

        jPanelContent.setBackground(new java.awt.Color(255, 255, 255));
        jPanelContent.setMaximumSize(new java.awt.Dimension(650, 456));
        jPanelContent.setMinimumSize(new java.awt.Dimension(650, 456));
        jPanelContent.setPreferredSize(new java.awt.Dimension(650, 456));

        javax.swing.GroupLayout jPanelContentLayout = new javax.swing.GroupLayout(jPanelContent);
        jPanelContent.setLayout(jPanelContentLayout);
        jPanelContentLayout.setHorizontalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelContentLayout.setVerticalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jButtConsultarSusc)
                .addGap(36, 36, 36)
                .addComponent(jButtAsignarSusc)
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtConsultarSusc, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(jButtAsignarSusc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtConsultarSuscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtConsultarSuscActionPerformed
        // TODO add your handling code here:
        JPanAdmSuscripcionConsultar pan = new JPanAdmSuscripcionConsultar();
        GUIFunctions.showPanel(pan, jPanelContent,650, 456);
        jButtConsultarSusc.setVisible(false);
        jButtAsignarSusc.setVisible(false);
        
    }//GEN-LAST:event_jButtConsultarSuscActionPerformed

    private void jButtAsignarSuscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtAsignarSuscActionPerformed
        // TODO add your handling code here:
        JPanAdmSuscripcionAsignar pan = new JPanAdmSuscripcionAsignar();
        GUIFunctions.showPanel(pan, jPanelContent,650, 456);
        jButtConsultarSusc.setVisible(false);
        jButtAsignarSusc.setVisible(false);
    }//GEN-LAST:event_jButtAsignarSuscActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtAsignarSusc;
    private javax.swing.JButton jButtConsultarSusc;
    private javax.swing.JPanel jPanelContent;
    // End of variables declaration//GEN-END:variables
}
