/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pandateam.sfsaludmaven.gui.panels;


/**
 *
 * @author biane
 */
public class JPanAdmServicioConsultar2 extends javax.swing.JPanel {

    /**
     * Creates new form JPanAdmPacientesConsultar
     */
    private static int idFilaSeleccionada = -1;
    
    public int getIdPacienteSeleccionado(){
        return idFilaSeleccionada;
    }
    
    public JPanAdmServicioConsultar2() {
        initComponents();
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabIDServicio = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabNombrePaciente = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabApellidoPaciente = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabDNIPaciente = new javax.swing.JLabel();
        jLabNombreCuidador = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabApellidoCuidador = new javax.swing.JLabel();
        jLabDNICuidador = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();

        jLabel4.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Nombre:");

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(650, 456));
        setMinimumSize(new java.awt.Dimension(650, 456));
        setPreferredSize(new java.awt.Dimension(650, 456));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Servicio:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 16, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Descripción:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 67, -1, -1));

        jLabIDServicio.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabIDServicio.setForeground(new java.awt.Color(0, 0, 0));
        jLabIDServicio.setText("-");
        add(jLabIDServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 16, 269, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("-");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 50, 366, 50));

        jLabel8.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Fecha de inicio:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 112, -1, -1));

        jLabel9.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("-");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 112, 189, -1));

        jLabel10.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("-");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 112, 177, -1));

        jLabel11.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Fecha de finalización:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 112, -1, -1));

        jLabel12.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Tipo:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 135, -1, -1));

        jLabel13.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("-");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 135, 270, -1));

        jLabel14.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("-");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 135, 240, -1));

        jLabel15.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Costo:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 135, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 164, 590, 10));

        jLabel2.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cuidador:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 192, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Paciente:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 192, -1, -1));

        jLabel16.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Nombre:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 220, -1, -1));

        jLabNombrePaciente.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabNombrePaciente.setForeground(new java.awt.Color(102, 102, 102));
        jLabNombrePaciente.setText("-");
        add(jLabNombrePaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 220, 216, -1));

        jLabel18.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Apellido:");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 243, -1, -1));

        jLabApellidoPaciente.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabApellidoPaciente.setForeground(new java.awt.Color(102, 102, 102));
        jLabApellidoPaciente.setText("-");
        add(jLabApellidoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 243, 216, -1));

        jLabel20.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("DNI:");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 266, -1, -1));

        jLabDNIPaciente.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabDNIPaciente.setForeground(new java.awt.Color(102, 102, 102));
        jLabDNIPaciente.setText("-");
        add(jLabDNIPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 266, 240, -1));

        jLabNombreCuidador.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabNombreCuidador.setForeground(new java.awt.Color(102, 102, 102));
        jLabNombreCuidador.setText("-");
        add(jLabNombreCuidador, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 220, 216, -1));

        jLabel23.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("Nombre:");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 220, -1, -1));

        jLabel24.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setText("Apellido:");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 243, -1, -1));

        jLabApellidoCuidador.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabApellidoCuidador.setForeground(new java.awt.Color(102, 102, 102));
        jLabApellidoCuidador.setText("-");
        add(jLabApellidoCuidador, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 243, 216, -1));

        jLabDNICuidador.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabDNICuidador.setForeground(new java.awt.Color(102, 102, 102));
        jLabDNICuidador.setText("-");
        add(jLabDNICuidador, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 266, 240, -1));

        jLabel27.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 102, 102));
        jLabel27.setText("DNI:");
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 266, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabApellidoCuidador;
    private javax.swing.JLabel jLabApellidoPaciente;
    private javax.swing.JLabel jLabDNICuidador;
    private javax.swing.JLabel jLabDNIPaciente;
    private javax.swing.JLabel jLabIDServicio;
    private javax.swing.JLabel jLabNombreCuidador;
    private javax.swing.JLabel jLabNombrePaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
