/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pandateam.sfsaludmaven.gui.panels;

import com.pandateam.sfsaludmaven.backend.dto.AtencionDTO;
import com.pandateam.sfsaludmaven.backend.dto.ServicioDTO;
import com.pandateam.sfsaludmaven.backend.managers.AtencionManager;
import com.pandateam.sfsaludmaven.backend.managers.ServicioManager;
import com.pandateam.sfsaludmaven.gui.GUIFunctions;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author biane
 */
public class JPanAdmServicioPresupuesto3 extends javax.swing.JPanel {

    /**
     * Creates new form JPanAdmPacientesConsultar
     */
    private static int idFilaSeleccionada = -1;
    private int servicioID;

    public void setServicioID(int servicioID) {
        this.servicioID = servicioID;
    }

    public int getIdPacienteSeleccionado() {
        return idFilaSeleccionada;
    }

    public JPanAdmServicioPresupuesto3(int id) throws SQLException {
        initComponents();
        servicioID = id;
        List <AtencionDTO> atenciones = new ArrayList();
        atenciones = AtencionManager.obtenerAtencionesDeServicio(id);
        int cantidadAtenciones=atenciones.size();
        double horas = AtencionManager.obtenerHorasDeAtenciones(atenciones);
        jLabCantAtenciones.setText(""+cantidadAtenciones);
        jLabCantHoras.setText(""+horas);
    }

    private double calcularPresupuesto() throws SQLException {
        // Aquí llamas al método para obtener y cargar los datos del servicio usando el ID
        ServicioDTO servicio = ServicioManager.verServicio(servicioID);
        Number costoXHoraValue = (Number) jSpinnerPrecioHora.getValue();
        double costoXHora = costoXHoraValue.doubleValue(); // Convertir a double
        return ServicioManager.calcularPresupuesto(servicio, costoXHora);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabCantAtenciones = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabCantHoras = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabCostoServicio = new javax.swing.JLabel();
        jSpinnerPrecioHora = new javax.swing.JSpinner();
        jButtonCalcular = new javax.swing.JButton();

        jLabel4.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Nombre:");

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(650, 456));
        setMinimumSize(new java.awt.Dimension(650, 456));
        setPreferredSize(new java.awt.Dimension(650, 456));

        jLabel1.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Presupuesto");

        jLabel5.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Se sumaron ");

        jLabCantAtenciones.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        jLabCantAtenciones.setForeground(new java.awt.Color(102, 102, 102));
        jLabCantAtenciones.setText("____");

        jLabel7.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("atenciones. En total son");

        jLabCantHoras.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        jLabCantHoras.setForeground(new java.awt.Color(102, 102, 102));
        jLabCantHoras.setText("____");

        jLabel9.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("horas.");

        jLabel10.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("El precio por hora es de");

        jLabel12.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("El costo del servicio es de");

        jLabCostoServicio.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        jLabCostoServicio.setForeground(new java.awt.Color(102, 102, 102));
        jLabCostoServicio.setText("___________");

        jSpinnerPrecioHora.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jButtonCalcular.setText("Calcular");
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jSpinnerPrecioHora))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabCantAtenciones)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabCantHoras)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jButtonCalcular))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabCostoServicio)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabCantAtenciones)
                            .addComponent(jLabel7)
                            .addComponent(jLabCantHoras)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSpinnerPrecioHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonCalcular)))
                .addGap(149, 149, 149)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabCostoServicio))
                .addContainerGap(161, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        try {
            double costo = calcularPresupuesto();
            jLabCostoServicio.setText(""+costo);
        } catch (SQLException ex) {
            Logger.getLogger(JPanAdmServicioPresupuesto3.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonCalcularActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JLabel jLabCantAtenciones;
    private javax.swing.JLabel jLabCantHoras;
    private javax.swing.JLabel jLabCostoServicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner jSpinnerPrecioHora;
    // End of variables declaration//GEN-END:variables
}
