/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pandateam.sfsaludmaven.gui.panels;

import com.pandateam.sfsaludmaven.gui.GUIFunctions;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author biane
 */
public class JPanAdmSuscripciones extends javax.swing.JPanel {

    /**
     * Creates new form JPanAdmServicios
     */
    
    public JPanAdmSuscripciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanContentSuscripciones = new javax.swing.JPanel();
        jPanButtonAsignarSuscripcion = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanButtonAgregarSuscripcion = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(650, 570));
        setMinimumSize(new java.awt.Dimension(650, 570));

        jLabel1.setFont(new java.awt.Font("Roboto Condensed", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setText("Administración de Suscripciones");

        jPanContentSuscripciones.setBackground(new java.awt.Color(255, 255, 255));
        jPanContentSuscripciones.setMaximumSize(new java.awt.Dimension(650, 500));
        jPanContentSuscripciones.setMinimumSize(new java.awt.Dimension(650, 500));
        jPanContentSuscripciones.setPreferredSize(new java.awt.Dimension(650, 500));

        jPanButtonAsignarSuscripcion.setBackground(new java.awt.Color(0, 128, 155));
        jPanButtonAsignarSuscripcion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanButtonAsignarSuscripcion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanButtonAsignarSuscripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanButtonAsignarSuscripcionMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Asignar Suscripción a un Paciente");
        jPanButtonAsignarSuscripcion.add(jLabel6);

        jPanButtonAgregarSuscripcion.setBackground(new java.awt.Color(0, 128, 155));
        jPanButtonAgregarSuscripcion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanButtonAgregarSuscripcion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanButtonAgregarSuscripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanButtonAgregarSuscripcionMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Agregar Suscripción");
        jPanButtonAgregarSuscripcion.add(jLabel7);

        javax.swing.GroupLayout jPanContentSuscripcionesLayout = new javax.swing.GroupLayout(jPanContentSuscripciones);
        jPanContentSuscripciones.setLayout(jPanContentSuscripcionesLayout);
        jPanContentSuscripcionesLayout.setHorizontalGroup(
            jPanContentSuscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanContentSuscripcionesLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(jPanContentSuscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanButtonAgregarSuscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanButtonAsignarSuscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanContentSuscripcionesLayout.setVerticalGroup(
            jPanContentSuscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanContentSuscripcionesLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jPanButtonAsignarSuscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanButtonAgregarSuscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(328, 328, 328))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanContentSuscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanContentSuscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPanButtonAsignarSuscripcionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanButtonAsignarSuscripcionMouseClicked
        // TODO add your handling code here:
        JPanAdmSuscripcionAsignar pan = new JPanAdmSuscripcionAsignar();
        GUIFunctions.showPanel(pan, jPanContentSuscripciones,650, 500);
        
    }//GEN-LAST:event_jPanButtonAsignarSuscripcionMouseClicked

    private void jPanButtonAgregarSuscripcionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanButtonAgregarSuscripcionMouseClicked
        // TODO add your handling code here:
        JPanAdmSuscripcionAgregar pan = new JPanAdmSuscripcionAgregar();
        GUIFunctions.showPanel(pan, jPanContentSuscripciones,650, 500);
    }//GEN-LAST:event_jPanButtonAgregarSuscripcionMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanButtonAgregarSuscripcion;
    private javax.swing.JPanel jPanButtonAsignarSuscripcion;
    private javax.swing.JPanel jPanContentSuscripciones;
    // End of variables declaration//GEN-END:variables
}
